### ISSUE TITLE
New episode not comming 

### ISSUE THREAD

**Issue by MetaHat** [KiriXen/zoro.to-clone#11]
New Episode not coming in api

**Comment by SailorSammyy** [comment]
> New Episode not coming in api

bcuz gogoanime isn't updating it, there's nothing i can do unless they do fix it

**Comment by MetaHat** [comment]
I know that's why I'm working on my Anito project. Invitation always there for you to join.

**Comment by SailorSammyy** [comment]
> I know that's why I'm working on my Anito project. Invitation always there for you to join.

i'll join u once i'm done with the zoro.to clone with new extra features and api

**Comment by Itsajay1411** [comment]
is api now working ?

**Comment by SailorSammyy** [comment]
> is api now working ?

nope seems like gogoanime is dead
