### ISSUE TITLE
Zoro.to

### ISSUE THREAD

**Issue by AnikatsuAnime** [KiriXen/zoro.to-clone#2]
When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/

**Comment by Anixer1** [comment]
> When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/

What did you do to work that site

**Comment by AnikatsuAnime** [comment]
> > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> 
> What did you do to work that site

I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me

**Comment by AnikatsuAnime** [comment]
Skygs

**Comment by AnikatsuAnime** [comment]
Hajsdj

**Comment by SailorSammyy** [comment]
> > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > 
> > 
> > What did you do to work that site
> 
> I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me

yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon

**Comment by AnikatsuAnime** [comment]
> > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > 
> > > 
> > > What did you do to work that site
> > 
> > 
> > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> 
> yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon

Hey try those file for your player 

https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV

**Comment by SailorSammyy** [comment]
> > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > 
> > > > 
> > > > What did you do to work that site
> > > 
> > > 
> > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > 
> > 
> > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> 
> Hey try those file for your player
> 
> https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV

well thank you for this but i've fixed the player and it's now runnin back like the usual

**Comment by anixer0** [comment]
> > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > 
> > > > > 
> > > > > What did you do to work that site
> > > > 
> > > > 
> > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > 
> > > 
> > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > 
> > 
> > Hey try those file for your player
> > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> 
> well thank you for this but i've fixed the player and it's now runnin back like the usual

Bro do have a player like this https://player.ryuk.to

**Comment by SailorSammyy** [comment]
> > > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > > 
> > > > > > 
> > > > > > What did you do to work that site
> > > > > 
> > > > > 
> > > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > > 
> > > > 
> > > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > > 
> > > 
> > > Hey try those file for your player
> > > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> > 
> > 
> > well thank you for this but i've fixed the player and it's now runnin back like the usual
> 
> Bro do have a player like this https://player.ryuk.to

yes

**Comment by anixer0** [comment]
> > > > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > > > 
> > > > > > > 
> > > > > > > What did you do to work that site
> > > > > > 
> > > > > > 
> > > > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > > > 
> > > > > 
> > > > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > > > 
> > > > 
> > > > Hey try those file for your player
> > > > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> > > 
> > > 
> > > well thank you for this but i've fixed the player and it's now runnin back like the usual
> > 
> > 
> > Bro do have a player like this https://player.ryuk.to
> 
> yes

Can you upload the code bro

**Comment by SailorSammyy** [comment]
> > > > > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What did you do to work that site
> > > > > > > 
> > > > > > > 
> > > > > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > > > > 
> > > > > > 
> > > > > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > > > > 
> > > > > 
> > > > > Hey try those file for your player
> > > > > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> > > > 
> > > > 
> > > > well thank you for this but i've fixed the player and it's now runnin back like the usual
> > > 
> > > 
> > > Bro do have a player like this https://player.ryuk.to
> > 
> > 
> > yes
> 
> Can you upload the code bro

it's already there on the player folder

**Comment by anixer0** [comment]
> > > > > > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > What did you do to work that site
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > > > > > 
> > > > > > > 
> > > > > > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > > > > > 
> > > > > > 
> > > > > > Hey try those file for your player
> > > > > > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> > > > > 
> > > > > 
> > > > > well thank you for this but i've fixed the player and it's now runnin back like the usual
> > > > 
> > > > 
> > > > Bro do have a player like this https://player.ryuk.to
> > > 
> > > 
> > > yes
> > 
> > 
> > Can you upload the code bro
> 
> it's already there on the player folder

Oh ok tnx

**Comment by SailorSammyy** [comment]
> > > > > > > > > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > What did you do to work that site
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> > > > > > > > 
> > > > > > > > 
> > > > > > > > yeah the player isn't workin anymore,might be bcuz i did some changes with the api and i'll try to fix this issue soon
> > > > > > > 
> > > > > > > 
> > > > > > > Hey try those file for your player
> > > > > > > https://drive.google.com/drive/folders/1EGByoj3Pr7Hl8diiIXUNSpi4u3rzzxgV
> > > > > > 
> > > > > > 
> > > > > > well thank you for this but i've fixed the player and it's now runnin back like the usual
> > > > > 
> > > > > 
> > > > > Bro do have a player like this https://player.ryuk.to
> > > > 
> > > > 
> > > > yes
> > > 
> > > 
> > > Can you upload the code bro
> > 
> > 
> > it's already there on the player folder
> 
> Oh ok tnx

no problem! 🤝

**Comment by SiAnime** [comment]
> > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > 
> > 
> > What did you do to work that site
> 
> I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me

how can you tell me im facing the same problem
![Capture](https://github.com/user-attachments/assets/008636a2-e53f-44db-a168-64f574f03023)

**Comment by anixer0** [comment]
> > > > When i tryed to host zoro.to clone on my own server it says can't handle this request when ever I try to open it https://anikatsu.free.nf/
> > > 
> > > 
> > > What did you do to work that site
> > 
> > 
> > I just added MySQL and it started working and also the streaming player that this script uses is not working so use your own that fetch and player anime from the api or use some one else's player if you want some one else's player reply me
> 
> how can you tell me im facing the same problem ![Capture](https://private-user-images.githubusercontent.com/187781427/384614935-008636a2-e53f-44db-a168-64f574f03023.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI5NDMsIm5iZiI6MTczMTI1MjY0MywicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0OTM1LTAwODYzNmEyLWU1M2YtNDRkYi1hMTY4LTY0ZjU3NGYwMzAyMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTMwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzdhYTU4ZTFkOWU5OWE0MTNmNjg5NzFlOWZjODEyYTU3NGM5ZDYwM2Q1YzA4YWY0Nzc5ZjgzNWFkNTVhOTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D_ebJBn0awNRWKnh7vpfyApNUzLMHLP5O8Ip57FEEPQ)

Create data base

**Comment by PacaHat** [comment]
Aniwave-web 

If you still can't fix it or setup any database then just remove or // out the $con MySQL code from your " _config.php " file it will fix your error but you can't use the login/register functions
