### ISSUE TITLE
There's an error on the page

### ISSUE THREAD

**Issue by anixer0** [KiriXen/zoro.to-clone#3]
Here's the link 

http://anixer.rf.gd/home

**Comment by AnikatsuAnime** [comment]
> Here's the link
> 
> http://anixer.rf.gd/home

What error

**Comment by SailorSammyy** [comment]
> Here's the link
> 
> http://anixer.rf.gd/home

is the error here the registration page?

**Comment by anixer0** [comment]
When I click the anime I want to watch this is always show

![Screenshot_20241008-194947](https://github.com/user-attachments/assets/a1b2dc57-bf57-4ebe-8eae-11c21396eab6)
![Screenshot_20241008-194947](https://github.com/user-attachments/assets/b28dbffa-b4ad-4511-afd9-659e95fbb899)

**Comment by SailorSammyy** [comment]
> When I click the anime I want to watch this is always show
> 
> ![Screenshot_20241008-194947](https://private-user-images.githubusercontent.com/172897096/374543845-a1b2dc57-bf57-4ebe-8eae-11c21396eab6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDU1MDgsIm5iZiI6MTcyOTE0NTIwOCwicGF0aCI6Ii8xNzI4OTcwOTYvMzc0NTQzODQ1LWExYjJkYzU3LWJmNTctNGViZS04ZWFlLTExYzIxMzk2ZWFiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjA2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQ3MDI0NDQ1NGVlMTZmMGY2ZjQ5NmRmZjg0OTE0YjUxYTljYzhhMDE1NGJlOTBjMjdhNmM4MTAyOTU2OWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6EvmOXoVsmxJxodtjsrxqRy3YqQt-WP4LhHKtQZD7Rk) ![Screenshot_20241008-194947](https://private-user-images.githubusercontent.com/172897096/374543939-b28dbffa-b4ad-4511-afd9-659e95fbb899.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDU1MDgsIm5iZiI6MTcyOTE0NTIwOCwicGF0aCI6Ii8xNzI4OTcwOTYvMzc0NTQzOTM5LWIyOGRiZmZhLWI0YWQtNDUxMS1hZmQ5LTY1OWU5NWZiYjg5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjA2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGE2YWJiNTc2OTE0MzA5ZDA3Njc0NGVkYzQ1MDA0OGI2YWI5NWEyZmQ3NGE2ZDM5OTM5MGQ2ZDhlMjFmYzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QbxtCEot_pRJ5474MYni1OtFQfTLlnHlVpleGFn_Gk)

it's a error by the mysql connection, check if u had given all the tables required

**Comment by anixer0** [comment]
> > When I click the anime I want to watch this is always show
> > ![Screenshot_20241008-194947](https://private-user-images.githubusercontent.com/172897096/374543845-a1b2dc57-bf57-4ebe-8eae-11c21396eab6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDU1MDgsIm5iZiI6MTcyOTE0NTIwOCwicGF0aCI6Ii8xNzI4OTcwOTYvMzc0NTQzODQ1LWExYjJkYzU3LWJmNTctNGViZS04ZWFlLTExYzIxMzk2ZWFiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjA2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQ3MDI0NDQ1NGVlMTZmMGY2ZjQ5NmRmZjg0OTE0YjUxYTljYzhhMDE1NGJlOTBjMjdhNmM4MTAyOTU2OWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6EvmOXoVsmxJxodtjsrxqRy3YqQt-WP4LhHKtQZD7Rk) ![Screenshot_20241008-194947](https://private-user-images.githubusercontent.com/172897096/374543939-b28dbffa-b4ad-4511-afd9-659e95fbb899.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDU1MDgsIm5iZiI6MTcyOTE0NTIwOCwicGF0aCI6Ii8xNzI4OTcwOTYvMzc0NTQzOTM5LWIyOGRiZmZhLWI0YWQtNDUxMS1hZmQ5LTY1OWU5NWZiYjg5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjA2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGE2YWJiNTc2OTE0MzA5ZDA3Njc0NGVkYzQ1MDA0OGI2YWI5NWEyZmQ3NGE2ZDM5OTM5MGQ2ZDhlMjFmYzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QbxtCEot_pRJ5474MYni1OtFQfTLlnHlVpleGFn_Gk)
> 
> it's a error by the mysql connection, check if u had given all the tables requ

 I fix the problem last month tnx😊
