### ISSUE TITLE
Can you please combine both sub and dub together?

### ISSUE THREAD

**Issue by Ratdevils** [KiriXen/zoro.to-clone#4]
Like this in the picture

![IMG_2563](https://github.com/user-attachments/assets/2644b790-0f72-4eb8-83ee-4ccef9b55e9b)

Also in watch page both sub and dub together.

![IMG_2564](https://github.com/user-attachments/assets/4c014395-8144-459c-801d-c636d95fe633)

You can add multiple api keys options. At least 4 Sources options in both sub and dub so the user can select. If one doesn’t one they can use others.

Aniwatch api and hianime mapper.

You can add few other apis like redis for caching. These  features will make your project better. by the way it’s amazing.

I hope that’s not too much to ask. Thanks

**Comment by BlazeCoderLab** [comment]
Well i'm also trying to accomplish this but not right now as i'm busy with my exams.
As for sub and dub it's easy. You just need to change little code in the main script not in the api. As for providers, it's difficult as in main api it give us just the hls url of that video.
Well i think @sam can do this means adding the direct servers other than just the hls url.

**Comment by Ratdevils** [comment]
It will be great if you can add these, and work on new features and upcoming updates for this project.

There is also comment section and few other things that can be improved.

**Comment by KiriXen** [comment]
> It will be great if you can add these, and work on new features and upcoming updates for this project.
> 
> There is also comment section and few other things that can be improved.

well i could try, but you prob need to wait until next year or when i have free time since i gotta study and all
