### ISSUE TITLE
Can you tell me how to use the jwplayer script file with react?

### ISSUE THREAD

**Issue by itzzzme** [KiriXen/zoro.to-clone#5]
i was trying to integrate the jwplayer with my react code so can you tell me how to do that

**Comment by SailorSammyy** [comment]
> i was trying to integrate the jwplayer with my react code so can you tell me how to do that

i'm not familiar with react.. you could check it out from here - https://github.com/jwplayer/jwplayer-react-native

**Comment by itzzzme** [comment]
> > i was trying to integrate the jwplayer with my react code so can you tell me how to do that
> 
> i'm not familiar with react.. you could check it out from here - https://github.com/jwplayer/jwplayer-react-native

But with any javascript framework a unique jwplayer script is needed if I use this jwplayer script will it be valid

**Comment by SailorSammyy** [comment]
> > > i was trying to integrate the jwplayer with my react code so can you tell me how to do that
> > 
> > 
> > i'm not familiar with react.. you could check it out from here - https://github.com/jwplayer/jwplayer-react-native
> 
> But with any javascript framework a unique jwplayer script is needed if I use this jwplayer script will it be valid

Well I'm not sure bout it but u could give it a try 👍

**Comment by itzzzme** [comment]
Thanks
