### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by SiAnime** [KiriXen/zoro.to-clone#6]
www.aniwatch.rf.gd is currently unable to handle this request.
![Capture](https://github.com/user-attachments/assets/b99a5600-3b06-4c0b-9242-819ef931e8ed)

**Comment by ErenYeager-AttackTitan** [comment]
> [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya



Are you using SQL server or not

**Comment by SailorSammyy** [comment]
> [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDUxNzYsIm5iZiI6MTczMTIwNDg3NiwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMjE0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzNjZTM2YTM2NTc3NTA1NDdlN2QyNmNjMDhjNTNkMjcyY2QwZjdlMzM1NTc2YTcxNTNkNTczNmM4MGI1ZTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0ic7a0Tymnx0DRdTVUZZFprZiC3jEj5hJX3kNm6V-w8)

Might be an error with the site or u made a mistake 🤷‍♂️

**Comment by SiAnime** [comment]
> > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> 
> Are you using SQL server or not

i upload website in infinityfree hosting platform

**Comment by SailorSammyy** [comment]
> > > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> > 
> > 
> > Are you using SQL server or not
> 
> i upload website in infinityfree hosting platform

did u create database and added what is needed on the _config.php along with the connection for the database?

**Comment by anixer0** [comment]
> > > > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> > > 
> > > 
> > > Are you using SQL server or not
> > 
> > 
> > i upload website in infinityfree hosting platform
> 
> did u create database and added what is needed on the _config.php along with the connection for the database?

The player isn't working always error

**Comment by SailorSammyy** [comment]
> > > > > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> > > > 
> > > > 
> > > > Are you using SQL server or not
> > > 
> > > 
> > > i upload website in infinityfree hosting platform
> > 
> > 
> > did u create database and added what is needed on the _config.php along with the connection for the database?
> 
> The player isn't working always error

u need proxy for the player

**Comment by SiAnime** [comment]
> > > > > > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> > > > > 
> > > > > 
> > > > > Are you using SQL server or not
> > > > 
> > > > 
> > > > i upload website in infinityfree hosting platform
> > > 
> > > 
> > > did u create database and added what is needed on the _config.php along with the connection for the database?
> > 
> > 
> > The player isn't working always error
> 
> u need proxy for the player

sir, thanks for instructions now my website is working
link:https://aniwatch.ct.ws/

**Comment by SailorSammyy** [comment]
> > > > > > > [www.aniwatch.rf.gd](http://www.aniwatch.rf.gd) is currently unable to handle this request. ![Capture](https://private-user-images.githubusercontent.com/187781427/384614544-b99a5600-3b06-4c0b-9242-819ef931e8ed.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUxNTgsIm5iZiI6MTczMTE2NDg1OCwicGF0aCI6Ii8xODc3ODE0MjcvMzg0NjE0NTQ0LWI5OWE1NjAwLTNiMDYtNGMwYi05MjQyLTgxOWVmOTMxZThlZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThmYTQ1NGVjYzgwMmUwYTVlN2JmNjk2MTFkNDVmNzgzMTUzYzNlNzY2ZGE5NjYxZTkzNDQ0NDZlZjRmYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEUjYMu_E4kO1xfdhBInp6v8ve3qq-IuuxNz0Ztya
> > > > > > 
> > > > > > 
> > > > > > Are you using SQL server or not
> > > > > 
> > > > > 
> > > > > i upload website in infinityfree hosting platform
> > > > 
> > > > 
> > > > did u create database and added what is needed on the _config.php along with the connection for the database?
> > > 
> > > 
> > > The player isn't working always error
> > 
> > 
> > u need proxy for the player
> 
> sir, thanks for instructions now my website is working link:https://aniwatch.ct.ws/

glad to hear that :)
