### ISSUE TITLE
Hey, Kirixen! There's an error in video streaming.

### ISSUE THREAD

**Issue by CUZAMARK** [KiriXen/zoro.to-clone#7]
I uploaded screenshot of error here, and yeah i tried both servers: 

![Screenshot_20241112_172842](https://github.com/user-attachments/assets/8b6feeec-5193-47d6-ab75-4b4cf12c9b55)

**Comment by CUZAMARK** [comment]
It's working when I visited the site using proxy, i think it's the file source url that's not working here or being blocked, that of (anzeat.pro)'s.

![Screenshot_(25)](https://github.com/user-attachments/assets/cffa9085-7d20-4717-9be3-f46671dfeffa)

**Comment by SailorSammyy** [comment]
> It's working when I visited the site using proxy, i think it's the file source url that's not working here or being blocked, that of (anzeat.pro)'s.
> 
> ![Screenshot_(25)](https://private-user-images.githubusercontent.com/110730813/385294972-cffa9085-7d20-4717-9be3-f46671dfeffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mjk1NTQsIm5iZiI6MTczMTQyOTI1NCwicGF0aCI6Ii8xMTA3MzA4MTMvMzg1Mjk0OTcyLWNmZmE5MDg1LTdkMjAtNDcxNy05YmUzLWY0NjY3MWRmZWZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNjM0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDJhZGVmNmEyOGEyMDEzMTAwZWVmZmQwMjRhNzIwMDA3ZmZjNTkwOTRkZTY4NmUyZjkyNTM2MmM4OTE5Y2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0bQh2dLwM_SHEm1gX6d7zT9QcfAtkrK_N-6SDb8dVIY)

Well u need to setup proxy inside the player while fetching the m3u8

**Comment by CUZAMARK** [comment]
Thanks, mate :)

**Comment by PacaHat** [comment]
Can you please share the code after fixing it

**Comment by SailorSammyy** [comment]
> Can you please share the code after fixing it

Sure I'll update it

**Comment by movieswithmahid** [comment]
Which api you are using

**Comment by SailorSammyy** [comment]
> Which api you are using

Api? For the whole website?

**Comment by movieswithmahid** [comment]
"https://github.com/kirixen/gogo-api" i haven’t notice this link that's why i ask for api. Sorry😶‍🌫️

But now i am getting another problem when i click on any anime or anything it’s showing 
![Screenshot_2024-11-16-19-30-24-19_c0dc27f5c07cb0fb3541d6073dfd6932](https://github.com/user-attachments/assets/ac261cb9-1221-4a5d-8d0b-8607458c13db)

'https://zoro.studyhub.site' this is the site link

**Comment by movieswithmahid** [comment]
> > Which api you are using
> 
> Api? For the whole website?



> "https://github.com/kirixen/gogo-api" i haven’t notice this link that's why i ask for api. Sorry😶‍🌫️
> 
> But now i am getting another problem when i click on any anime or anything it’s showing ![Screenshot_2024-11-16-19-30-24-19_c0dc27f5c07cb0fb3541d6073dfd6932](https://private-user-images.githubusercontent.com/185796959/386848281-ac261cb9-1221-4a5d-8d0b-8607458c13db.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjQ0MDIsIm5iZiI6MTczMTc2NDEwMiwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODQ4MjgxLWFjMjYxY2I5LTEyMjEtNGE1ZC04ZDBiLTg2MDc0NThjMTNkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWRkNjM1NDFkMDQ4NDkzNzUyOTVlZWZhMDE2YWIzNjk1Yjk3NmI2MWIyOTQ0N2UxMjQ0ODU3OWRjOWZkODIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JuL46MvaItMwDce_BRPTPx5CN6gXNsJCvsuj9q_RoGo)
> 
> 'https://zoro.studyhub.site' this is the site link

I got it what's the problem it’s an issue of .htaccess and i solve it

**Comment by MetaHat** [comment]
The player still not working

**Comment by CUZAMARK** [comment]
I have implemented proxy into 2nd player (v2.php) , code's here  on pastbin : [https://pastebin.com/MQGHawY5](https://pastebin.com/MQGHawY5)

&
Here's v1.php:
[https://pastebin.com/6PqaEWd2](https://pastebin.com/6PqaEWd2)

**Comment by MetaHat** [comment]
its working but too slow 
V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7
V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7

can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ

**Comment by CUZAMARK** [comment]
It seems like a network issue on your end, as both versions are working fine for me.

**Comment by MetaHat** [comment]
may be but my internet speed is fast have you look on the code that i shared 
and can we connect

**Comment by movieswithmahid** [comment]
> its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> 
> can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ

I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed

**Comment by MetaHat** [comment]
> > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> 
> I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed

can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari

**Comment by CUZAMARK** [comment]
> > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > 
> > 
> > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> 
> can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari

try using this code (it's only **php**, replace it with the old one and see if it works...):
[https://pastebin.com/qkXsk5cp](https://pastebin.com/qkXsk5cp)

**Comment by MetaHat** [comment]
> > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > 
> > > 
> > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > 
> > 
> > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> 
> try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp

only white screen show i checked the old code its working fine through my mobile data but slow on my wifi

**Comment by movieswithmahid** [comment]
> > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > 
> > 
> > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> 
> can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari

Check

**Comment by MetaHat** [comment]
> > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > 
> > > 
> > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > 
> > 
> > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> 
> Check

yup replied you

**Comment by movieswithmahid** [comment]
> > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > 
> > > 
> > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > 
> > 
> > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> 
> try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp

I Don't think it will speed up Videos

**Comment by MetaHat** [comment]
> > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > 
> > > 
> > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > 
> > 
> > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> 
> try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp

which api you used it shows names in english

**Comment by CUZAMARK** [comment]
> > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > 
> > > > 
> > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > 
> > > 
> > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > 
> > 
> > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> 
> I Don't think it will speed up Videos

I’ve made some error handling and validation changes. The speed largely depends on the proxy and the network being used.

**Comment by MetaHat** [comment]
> > > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > > 
> > > > > 
> > > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > > 
> > > > 
> > > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > > 
> > > 
> > > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> > 
> > 
> > I Don't think it will speed up Videos
> 
> I’ve made some error handling and validation changes. The speed largely depends on the proxy and the network being used.

how your website shows names in english

**Comment by CUZAMARK** [comment]
> > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > 
> > > > 
> > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > 
> > > 
> > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > 
> > 
> > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> 
> only white screen show i checked the old code its working fine through my mobile data but slow on my wifi

The issue is that the PHP code I provided should only replace the PHP portion written before `<!DOCTYPE html>`. The rest of the code (starting from `<!DOCTYPE html>`) should remain unchanged.

**Comment by CUZAMARK** [comment]
> > > > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > > > 
> > > > > > 
> > > > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > > > 
> > > > > 
> > > > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > > > 
> > > > 
> > > > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> > > 
> > > 
> > > I Don't think it will speed up Videos
> > 
> > 
> > I’ve made some error handling and validation changes. The speed largely depends on the proxy and the network being used.
> 
> how your website shows names in english

Which website are you talking about?

**Comment by MetaHat** [comment]
> > > > > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > > > > 
> > > > > > > 
> > > > > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > > > > 
> > > > > > 
> > > > > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > > > > 
> > > > > 
> > > > > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> > > > 
> > > > 
> > > > I Don't think it will speed up Videos
> > > 
> > > 
> > > I’ve made some error handling and validation changes. The speed largely depends on the proxy and the network being used.
> > 
> > 
> > how your website shows names in english
> 
> Which website are you talking about?

https://zoro.studyhub.site/ see latest subbed

**Comment by CUZAMARK** [comment]
> > > > > > > > > its working but too slow V1 = https://anixtv.in/player/v1.php?id=blue-lock-vs-u-20-japan-episode-7 V2 = https://anixtv.in/player/v2.php?id=blue-lock-vs-u-20-japan-episode-7
> > > > > > > > > can you please look at my code and tell the error https://pastebin.com/qjpXNLBJ
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I think the issue with your proxy server you can check my 'https://zoro.studyhub.site/watch/blue-lock-vs-u-20-japan-episode-1' demo site and check Both one's speed
> > > > > > > 
> > > > > > > 
> > > > > > > can we connect ? through telegram here is my profile https://t.me/Siddhartha_Tiwari
> > > > > > 
> > > > > > 
> > > > > > try using this code (it's only **php**, replace it with the old one and see if it works...): https://pastebin.com/qkXsk5cp
> > > > > 
> > > > > 
> > > > > I Don't think it will speed up Videos
> > > > 
> > > > 
> > > > I’ve made some error handling and validation changes. The speed largely depends on the proxy and the network being used.
> > > 
> > > 
> > > how your website shows names in english
> > 
> > 
> > Which website are you talking about?
> 
> https://zoro.studyhub.site/ see latest subbed

It's not my site and what's the issue with latest subbed ?

**Comment by SailorSammyy** [comment]
Btw guys might be an issue with the roxy itself sometimes, I recommend u guys finding other proxies if u want it to be fast
