### ISSUE TITLE
Hello, Kirixen! I Got an Error on video player page

### ISSUE THREAD

**Issue by movieswithmahid** [KiriXen/zoro.to-clone#8]
![Screenshot_2024-11-16-19-45-50-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a26e8402-81ea-4572-8dbc-aa50c4d17f58)
![Screenshot_2024-11-16-19-45-56-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/2083d36e-8f2e-4078-ba30-4800de886687)
![Screenshot_2024-11-16-19-47-39-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5e7c6886-6ff5-44bd-b95d-a8d93a76b0e9)
![Screenshot_2024-11-16-19-47-53-05_33f34bf0029ca15359ebd43d4b95def2](https://github.com/user-attachments/assets/81f30a48-4782-4d05-8e23-fe1c972948a8)

When i try to go on video player page then It's not working i am trying using different Browsers but still not working

**Comment by ErenYeager-AttackTitan** [comment]
> ![Screenshot_2024-11-16-19-45-50-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850272-a26e8402-81ea-4572-8dbc-aa50c4d17f58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjcyLWEyNmU4NDAyLTgxZWEtNDU3Mi04ZGJjLWFhNTBjNGQxN2Y1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWNkNTU0YjkyYWFmYjk4MGNhZGI3N2FlMDRhYTYxY2M5ZTFjOGJmZjFmMzNiMTRlM2E0ZTE1Y2U3NDQ2MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qe1bQWfBrErzIwEuWyUVOckb8oByWOCq0SVyUWUcH3o) ![Screenshot_2024-11-16-19-45-56-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850274-2083d36e-8f2e-4078-ba30-4800de886687.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjc0LTIwODNkMzZlLThmMmUtNDA3OC1iYTMwLTQ4MDBkZTg4NjY4Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzJkZTQxMDc2NGY1ZGU1NTQ1MzZhZTE2ZjEyMzBkYTQzYmRkOTk4MjAxY2VjOTNiZDc2ZDU0ZTdhYWYyM2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3q1ODRXWUI2QYzdFdxkztXOOv6KZqazjcjkXfw6Hmok) ![Screenshot_2024-11-16-19-47-39-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850276-5e7c6886-6ff5-44bd-b95d-a8d93a76b0e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjc2LTVlN2M2ODg2LTZmZjUtNDRiZC1iOTVkLWE4ZDkzYTc2YjBlOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzQyZDMyNzljOWIzY2ZiYjkzYjA4MmE0NzlkYWViMGRkODgyMjgyN2YzZWQxZDA0YWRmYWU4NmU5ODI1MmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GDdHwehYjrCQ4opMIAbzsaYRHLS5j6q5LEaq9DErLd8) ![Screenshot_2024-11-16-19-47-53-05_33f34bf0029ca15359ebd43d4b95def2](https://private-user-images.githubusercontent.com/185796959/386850280-81f30a48-4782-4d05-8e23-fe1c972948a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjgwLTgxZjMwYTQ4LTQ3ODItNGQwNS04ZTIzLWZlMWM5NzI5NDhhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTE4ZGEwYTUzM2Q5ZTI5ODA5NDgyZjIxZDc0ODE1Y2Q2YzBmZWIwYTFjYzNjMDVlODIzMDdlZjUxYjhkYjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iEY712PljcLSEpC_ogq8KLIeTl9BjsdV78y7YtXpprw)
> 
> When i try to go on video player page then It's not working i am trying using different Browsers but



I think you delete your .htaccess file

**Comment by movieswithmahid** [comment]
> > ![Screenshot_2024-11-16-19-45-50-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850272-a26e8402-81ea-4572-8dbc-aa50c4d17f58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjcyLWEyNmU4NDAyLTgxZWEtNDU3Mi04ZGJjLWFhNTBjNGQxN2Y1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWNkNTU0YjkyYWFmYjk4MGNhZGI3N2FlMDRhYTYxY2M5ZTFjOGJmZjFmMzNiMTRlM2E0ZTE1Y2U3NDQ2MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qe1bQWfBrErzIwEuWyUVOckb8oByWOCq0SVyUWUcH3o) ![Screenshot_2024-11-16-19-45-56-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850274-2083d36e-8f2e-4078-ba30-4800de886687.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjc0LTIwODNkMzZlLThmMmUtNDA3OC1iYTMwLTQ4MDBkZTg4NjY4Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzJkZTQxMDc2NGY1ZGU1NTQ1MzZhZTE2ZjEyMzBkYTQzYmRkOTk4MjAxY2VjOTNiZDc2ZDU0ZTdhYWYyM2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3q1ODRXWUI2QYzdFdxkztXOOv6KZqazjcjkXfw6Hmok) ![Screenshot_2024-11-16-19-47-39-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/185796959/386850276-5e7c6886-6ff5-44bd-b95d-a8d93a76b0e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjc2LTVlN2M2ODg2LTZmZjUtNDRiZC1iOTVkLWE4ZDkzYTc2YjBlOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzQyZDMyNzljOWIzY2ZiYjkzYjA4MmE0NzlkYWViMGRkODgyMjgyN2YzZWQxZDA0YWRmYWU4NmU5ODI1MmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GDdHwehYjrCQ4opMIAbzsaYRHLS5j6q5LEaq9DErLd8) ![Screenshot_2024-11-16-19-47-53-05_33f34bf0029ca15359ebd43d4b95def2](https://private-user-images.githubusercontent.com/185796959/386850280-81f30a48-4782-4d05-8e23-fe1c972948a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQzODgsIm5iZiI6MTczMTc3NDA4OCwicGF0aCI6Ii8xODU3OTY5NTkvMzg2ODUwMjgwLTgxZjMwYTQ4LTQ3ODItNGQwNS04ZTIzLWZlMWM5NzI5NDhhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTE4ZGEwYTUzM2Q5ZTI5ODA5NDgyZjIxZDc0ODE1Y2Q2YzBmZWIwYTFjYzNjMDVlODIzMDdlZjUxYjhkYjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iEY712PljcLSEpC_ogq8KLIeTl9BjsdV78y7YtXpprw)
> > When i try to go on video player page then It's not working i am trying using different Browsers but
> 
> I think you delete your .htaccess file

No, It's an mysql problem and i solved it
