### ISSUE TITLE
Make a new project 

### ISSUE THREAD

**Issue by MetaHat** [KiriXen/zoro.to-clone#9]
Hi KiriXen, 
I am working on a new project based on aniwatch api as i am a beginner in php i need some help so would you like to work with me on this project 
Here is the link all the the process i make soo far 
https://zoro.tohost.site  
Waiting For Your Response...

**Comment by SailorSammyy** [comment]
> I am working on a new project based on aniwatch api as i am a beginner in php i need some help so would you like to work with me on this project

that seems cool, sure I could help you and all but rn for me time is very valuable, i need to focus on the outside world first!

well just hit me up on discord (username - kirixen)

**Comment by MetaHat** [comment]
Well i am not on discord can we use telegram

**Comment by CUZAMARK** [comment]
Not sure if you've seen it already or not but here is one project named AnimeDex-Lite ([https://github.com/TechShreyash/AnimeDexLite](https://github.com/TechShreyash/AnimeDexLite))
It's pretty similar as yours , maybe you can take some references.

**Comment by SailorSammyy** [comment]
> Well i am not on discord can we use telegram

We will talk bout this later, for now im focusing more on my new project

**Comment by MetaHat** [comment]
> Not sure if you've seen it already or not but here is one project named AnimeDex-Lite (https://github.com/TechShreyash/AnimeDexLite) It's pretty similar as yours , maybe you can take some references.

Thanks it would be a big help also can you work with me in fixing the player and changing sub and dub in this project
